--all Query's 

CREATE TABLE IF NOT EXISTS users (
    "userId" SERIAL PRIMARY KEY UNIQUE,
    "userName" VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(100) UNIQUE NOT NULL
);

ALTER TABLE users ADD COLUMN avatar JSONB;

ALTER TABLE users ADD COLUMN "resetPasswordToken" VARCHAR(100);

ALTER TABLE users ADD COLUMN "resetPasswordExpire" TIMESTAMP;
